<?php

namespace AppBundle\Repository;

/**
 * ArretaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArretaRepository extends \Doctrine\ORM\EntityRepository
{
}
