<?php

namespace AppBundle\Repository;


/**
 * ArretaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArretaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllFetched()
    {

        return $this->createQueryBuilder( 'a' )
                    ->leftJoin( 'a.user', 'u' )
                    ->addSelect( 'u' )
                    ->leftJoin( 'a.tramiteak', 't' )
                    ->addSelect( 't' )
                    ->leftJoin('u.barrutia', 'b')
                    ->addSelect('b')
                    ->getQuery()
                    ->getResult();

    }

    public function findMyAll( $id )
    {
        $em = $this->getEntityManager();
        $sql = /** @lang text */
            "SELECT a
                FROM AppBundle:Arreta a
                INNER JOIN a.user u
                WHERE u.id = :id
                ORDER BY a.id DESC
        ";

        $consulta = $em->createQuery( $sql );
        $consulta->setParameter( 'id', $id );

        return $consulta->getResult();

    }

    public function bilatzailea( $hasi = null, $fin = null, $closed = null )
    {
        $em = $this->getEntityManager();


        $sql = /** @lang text */
            "
            SELECT a
                FROM AppBundle:Arreta a
                WHERE                 
        ";

        $where = "";
        if ( strlen( $hasi ) > 0 ) {
            $where = $where . "a.fetxa > :hasi ";
        }
        if ( strlen( $fin ) > 0 ) {
            if ( strlen( $where ) > 0 ) {
                $where = $where . " AND a.fetxa < :fin ";
            } else {
                $where = $where . "a.fetxa < :fin ";
            }
        }
        if ( strlen( $closed ) > 0 ) {
            if ( strlen( $where ) > 0 ) {
                $where = $where . "AND a.isclosed = :closed";
            } else {
                $where = $where . "a.isclosed = :closed";
            }
        }


        $consulta = $em->createQuery( $sql . $where );

        if ( strlen( $hasi ) > 0 ) {
            $consulta->setParameter( 'hasi', $hasi );
        }
        if ( strlen( $fin ) > 0 ) {
            $consulta->setParameter( 'fin', $fin );
        }
        if ( strlen( $closed ) > 0 ) {
            $consulta->setParameter( 'closed', $closed );
        }


        return $consulta->getResult();

    }

    public function findGaurkoArretaKopurua( $userid = null )
    {

        if ( isset( $userid ) ) {
            $em = $this->getEntityManager();
            $d = new \DateTime();
            $sql = /** @lang text */
                "
            SELECT count(a) as zenbat
                FROM AppBundle:Arreta a
                INNER JOIN a.user u
                WHERE a.fetxa > :date_start and a.fetxa < :date_end and u.id = :userid                 
            ";

            $consulta = $em->createQuery( $sql );
            $date = new \DateTime();
            $consulta->setParameter( 'date_start', $date->format( 'Y-m-d 00:00:00' ) );
            $consulta->setParameter( 'date_end', $date->format( 'Y-m-d 23:59:59' ) );
            $consulta->setParameter( 'userid', $userid );

            return $consulta->getResult();
        } else {
            $em = $this->getEntityManager();
            $d = new \DateTime();
            $sql = /** @lang text */
                "
            SELECT count(a) as zenbat
                FROM AppBundle:Arreta a
                WHERE a.fetxa > :date_start and a.fetxa < :date_end                 
            ";

            $consulta = $em->createQuery( $sql );
            $date = new \DateTime();
            $consulta->setParameter( 'date_start', $date->format( 'Y-m-d 00:00:00' ) );
            $consulta->setParameter( 'date_end', $date->format( 'Y-m-d 23:59:59' ) );


            return $consulta->getSingleScalarResult();
        }

    }

}
