<?php

namespace AppBundle\Repository;

/**
 * KanalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KanalaRepository extends \Doctrine\ORM\EntityRepository
{
}
