<?php

namespace AppBundle\Repository;

/**
 * MotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotaRepository extends \Doctrine\ORM\EntityRepository
{
}
