barrutia:
    path: /barrutia
    defaults: { _controller: AppBundle:Default:barrutia }

app:
    resource: '@AppBundle/Controller/'
    prefix: /{_locale}
    type: annotation
    requirements:
        _locale: "|es|eu"
    defaults:
        _locale: 'eu'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"